# Generated by Django 2.1.7 on 2019-03-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('arrived', models.DateTimeField(null=True)),
                ('symptoms', models.TextField(null=True)),
                ('diagnos', models.TextField(null=True)),
            ],
        ),
    ]
